# Generated by Django 5.0.6 on 2024-06-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreApp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='author_pseudonym',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
